### ISSUE TITLE
build:project:create fails

### ISSUE THREAD

**Issue by ataylorme** [pantheon-systems/terminus-build-tools-plugin#102] opened 2017-09-07 21:59 UTC
Fails with and without `--git=bitbucket`. I was able to build with BitBucket before I went on vacation. Using the commit `e8b82d858daeb39a9d786c4dced165f154a25633` (`2.0.0-alpha2`) works, so the issue was sometime between now and then.

```
terminus build:project:create pantheon-systems/example-wordpress-composer:dev-master testbitbucketbuild --label='Test Bitbucket Build' --git=bitbucket
PHP Fatal error:  Interface 'Pantheon\TerminusBuildTools\ServiceProviders\Bitbucket\RepositoryProviders\GitProvider' not found in /Users/andrewtaylor/.terminus/plugins/terminus-build-tools-plugin/src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php on line 19
PHP Stack trace:
PHP   1. {main}() /Users/andrewtaylor/pantheon-cli/bin/terminus:0
PHP   2. Pantheon\Terminus\Terminus->run() /Users/andrewtaylor/pantheon-cli/bin/terminus:44
PHP   3. Robo\Runner->run() /Users/andrewtaylor/pantheon-cli/src/Terminus.php:103
PHP   4. Symfony\Component\Console\Application->run() /Users/andrewtaylor/pantheon-cli/vendor/consolidation/robo/src/Runner.php:167
PHP   5. Symfony\Component\Console\Application->doRun() /Users/andrewtaylor/pantheon-cli/vendor/symfony/console/Application.php:130
PHP   6. Symfony\Component\Console\Application->doRunCommand() /Users/andrewtaylor/pantheon-cli/vendor/symfony/console/Application.php:228
PHP   7. Consolidation\AnnotatedCommand\AnnotatedCommand->run() /Users/andrewtaylor/pantheon-cli/vendor/symfony/console/Application.php:892
PHP   8. Consolidation\AnnotatedCommand\AnnotatedCommand->initialize() /Users/andrewtaylor/pantheon-cli/vendor/symfony/console/Command/Command.php:229
PHP   9. Consolidation\AnnotatedCommand\CommandProcessor->initializeHook() /Users/andrewtaylor/pantheon-cli/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:381
PHP  10. Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize() /Users/andrewtaylor/pantheon-cli/vendor/consolidation/annotated-command/src/CommandProcessor.php:117
PHP  11. Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook() /Users/andrewtaylor/pantheon-cli/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:27
PHP  12. Pantheon\TerminusBuildTools\Commands\ProjectCreateCommand->validateSiteName() /Users/andrewtaylor/pantheon-cli/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:37
PHP  13. Pantheon\TerminusBuildTools\Commands\ProjectCreateCommand->createProviders() /Users/andrewtaylor/.terminus/plugins/terminus-build-tools-plugin/src/Commands/ProjectCreateCommand.php:59
PHP  14. Pantheon\TerminusBuildTools\ServiceProviders\ProviderManager->createProvider() /Users/andrewtaylor/.terminus/plugins/terminus-build-tools-plugin/src/Commands/BuildToolsBase.php:82
PHP  15. class_exists() /Users/andrewtaylor/.terminus/plugins/terminus-build-tools-plugin/src/ServiceProviders/ProviderManager.php:70
PHP  16. spl_autoload_call() /Users/andrewtaylor/.terminus/plugins/terminus-build-tools-plugin/src/ServiceProviders/ProviderManager.php:70
PHP  17. Composer\Autoload\ClassLoader->loadClass() /Users/andrewtaylor/.terminus/plugins/terminus-build-tools-plugin/src/ServiceProviders/ProviderManager.php:70
PHP  18. Composer\Autoload\includeFile() /Users/andrewtaylor/pantheon-cli/vendor/composer/ClassLoader.php:322
PHP  19. include() /Users/andrewtaylor/pantheon-cli/vendor/composer/ClassLoader.php:444

Fatal error: Interface 'Pantheon\TerminusBuildTools\ServiceProviders\Bitbucket\RepositoryProviders\GitProvider' not found in /Users/andrewtaylor/.terminus/plugins/terminus-build-tools-plugin/src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php on line 19

Call Stack:
    0.0050     365368   1. {main}() /Users/andrewtaylor/pantheon-cli/bin/terminus:0
    0.0958    5653248   2. Pantheon\Terminus\Terminus->run() /Users/andrewtaylor/pantheon-cli/bin/terminus:44
    0.0958    5653272   3. Robo\Runner->run() /Users/andrewtaylor/pantheon-cli/src/Terminus.php:103
   11.6237   10473712   4. Symfony\Component\Console\Application->run() /Users/andrewtaylor/pantheon-cli/vendor/consolidation/robo/src/Runner.php:167
   11.6316   10474224   5. Symfony\Component\Console\Application->doRun() /Users/andrewtaylor/pantheon-cli/vendor/symfony/console/Application.php:130
   11.6323   10474224   6. Symfony\Component\Console\Application->doRunCommand() /Users/andrewtaylor/pantheon-cli/vendor/symfony/console/Application.php:228
   11.6370   10512992   7. Consolidation\AnnotatedCommand\AnnotatedCommand->run() /Users/andrewtaylor/pantheon-cli/vendor/symfony/console/Application.php:892
   11.6376   10514200   8. Consolidation\AnnotatedCommand\AnnotatedCommand->initialize() /Users/andrewtaylor/pantheon-cli/vendor/symfony/console/Command/Command.php:229
   11.6377   10514576   9. Consolidation\AnnotatedCommand\CommandProcessor->initializeHook() /Users/andrewtaylor/pantheon-cli/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:381
   11.6381   10519184  10. Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize() /Users/andrewtaylor/pantheon-cli/vendor/consolidation/annotated-command/src/CommandProcessor.php:117
   11.6383   10519560  11. Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook() /Users/andrewtaylor/pantheon-cli/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:27
   11.6383   10519560  12. Pantheon\TerminusBuildTools\Commands\ProjectCreateCommand->validateSiteName() /Users/andrewtaylor/pantheon-cli/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:37
   11.6384   10519560  13. Pantheon\TerminusBuildTools\Commands\ProjectCreateCommand->createProviders() /Users/andrewtaylor/.terminus/plugins/terminus-build-tools-plugin/src/Commands/ProjectCreateCommand.php:59
   12.6712   11357248  14. Pantheon\TerminusBuildTools\ServiceProviders\ProviderManager->createProvider() /Users/andrewtaylor/.terminus/plugins/terminus-build-tools-plugin/src/Commands/BuildToolsBase.php:82
   12.6713   11357248  15. class_exists() /Users/andrewtaylor/.terminus/plugins/terminus-build-tools-plugin/src/ServiceProviders/ProviderManager.php:70
   12.6713   11357504  16. spl_autoload_call() /Users/andrewtaylor/.terminus/plugins/terminus-build-tools-plugin/src/ServiceProviders/ProviderManager.php:70
   12.6714   11357632  17. Composer\Autoload\ClassLoader->loadClass() /Users/andrewtaylor/.terminus/plugins/terminus-build-tools-plugin/src/ServiceProviders/ProviderManager.php:70
   12.6714   11357824  18. Composer\Autoload\includeFile() /Users/andrewtaylor/pantheon-cli/vendor/composer/ClassLoader.php:322
   12.6718   11389096  19. include('/Users/andrewtaylor/.terminus/plugins/terminus-build-tools-plugin/src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php') /Users/andrewtaylor/pantheon-cli/vendor/composer/ClassLoader.php:444
```

**Comment by greg-1-anderson** [comment] 2017-09-07 22:08
Hm, AFAIK the tests are still passing. I'll give it a try locally.

**Comment by greg-1-anderson** [comment] 2017-09-07 22:11
Drupal test seems to be working. Will try WordPress next.

**Comment by greg-1-anderson** [comment] 2017-09-07 22:16
Drupal build failed due to a "Network is unreachable" error.

My wp build failed because the example wp composer project couldn't be installed.

```
Installing pantheon-systems/example-wordpress-composer (dev-master e63183dfc6dcc2fe532e19108acdaa8b97cee6f8)
  - Installing pantheon-systems/example-wordpress-composer (dev-master master): Cloning master from cache
Created project in new-wp-foo-test
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for doctrine/instantiator 1.1.0 -> satisfiable by doctrine/instantiator[1.1.0].
    - doctrine/instantiator 1.1.0 requires php ^7.1 -> your PHP version (5.6.25) does not satisfy that requirement.
```

I could fix this by updating to php 7.1.  I'll make a PR in the example wp project to fix this.

**Comment by greg-1-anderson** [comment] 2017-09-07 22:16
But as for the original report, doesn't seem to be happening for me. Maybe try moving your sources away, and re-install? I am using latest HEAD of master (03faf194).

**Comment by greg-1-anderson** [comment] 2017-09-07 22:27
Related PR: https://github.com/pantheon-systems/example-wordpress-composer/pull/34

**Comment by ataylorme** [comment] 2017-09-07 22:33
> Maybe try moving your sources away, and re-install?

I've tried nuking it and re-installing, issue persists. This was originally found by @davidneedham, I just opened the issue when I was able to recreate.

**Comment by greg-1-anderson** [comment] 2017-09-07 22:41
Are you using 03faf19?

**Comment by greg-1-anderson** [comment] 2017-09-07 22:42
Hm, I found the problem in the source. Not sure why it is a problem for you and not me. Oh, maybe php 7.1 is more strict. Anyway, I can fix it now.

**Comment by stevector** [comment] 2017-09-07 22:42
I haven't tried to reproduce but I think I see the problem:

```
use Pantheon\TerminusBuildTools\ServiceProviders\RepositoryProviders\GitProvider;
```

That line is present in https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/master/src/ServiceProviders/RepositoryProviders/GitHub/GitHubProvider.php

but not https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/master/src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php

**Comment by greg-1-anderson** [comment] 2017-09-07 22:51
https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/103

**Comment by ataylorme** [comment] 2017-09-08 15:52
@davidneedham and I are both running `7.1.x` and it does seem to be stricter. With the `use` fix implemented it now returns

```
PHP Fatal error:  Class Pantheon\TerminusBuildTools\ServiceProviders\Bitbucket\RepositoryProviders\BitbucketProvider contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Pantheon\TerminusBuildTools\ServiceProviders\RepositoryProviders\GitProvider::deleteRepository) in /Users/davidneedham/.terminus/plugins/terminus-build-tools-plugin/src/ServiceProviders/RepositoryProviders/Bitbucket/BitbucketProvider.php on line 20
```

**Comment by greg-1-anderson** [comment] 2017-09-08 16:16
I'd better switch back to PHP 7.1 so that I can fix this properly. It takes five or ten seconds, but I'll take that sacrifice.  :P

**Comment by greg-1-anderson** [comment] 2017-09-08 21:57
Hm, I was able to successfully create a d8 and wp site with php 7.1 using #103. Implementing abstract methods shouldn't be optional under any php config settings, I wouldn't think.

In any event, I found the missing `deleteRepository()` and added a stub repository in #103.

**Comment by greg-1-anderson** [comment] 2017-09-08 22:12
Merged #103. Hopefully this clears up everyone's problems.

**Comment by davidneedham** [comment] 2017-09-09 05:49
I'm still seeing an error when I run `terminus build:project:create d8 randomsitename --git="bitbucket"` using master:
```[Exception]
  Could not load class \Pantheon\TerminusBuildTools\ServiceProviders\Reposito
  ryProviders\Bitbucket\BitbucketProvider```

**Comment by LukasRos** [comment] 2017-09-11 08:30
Current master has an incorrect `namespace` declaration in `BitbucketProvider.php`. I'm fixing this with my next PR.

**Comment by stevector** [comment] 2017-10-18 20:17
> Current master has an incorrect namespace declaration in BitbucketProvider.php. I'm fixing this with my next PR.

@LukasRos Was that fixed here? https://github.com/pantheon-systems/terminus-build-tools-plugin/pull/107/files#diff-a39100c401681ff242854edb6766562aR3

Can this issue be closed?

**Comment by greg-1-anderson** [comment] 2017-10-18 21:40
This issue has collected a number of unrelated problems with similar-looking symptoms. I think most of these have been fixed, but if any remain, let's open new issues to track them.

**Closed by greg-1-anderson** 2017-10-18 21:40 UTC
