### ISSUE TITLE
build:env:push is incompatible with the recent 2.1.0 release of Terminus

### ISSUE THREAD

**Issue by zserno** [pantheon-systems/terminus-build-tools-plugin#250] opened 2019-09-05 11:12 UTC
We have been using a custom Gitlab CI for months to deploy to a Drupal 8 site hosted at Pantheon, with no problems until today. We started to receive the following error at the last step of our deploy process (using Terminus v2.1.0 and Terminus Build Tools Plugin v2.0.0-beta15):

```
$ terminus build-env:push-code $TERMINUS_SITE.dev

In ComposerDependencyValidator.php line 106:
                                                                               
  The plugin pantheon-systems/terminus-build-tools-plugin has installed the p  
  roject phpspec/prophecy: 1.8.0, but Terminus has installed phpspec/prophecy  
  : 1.8.1. To resolve this, try running 'composer update' in both the plugin   
  directory, and the terminus directory.                                       
                                                                              
```

This is because a new version of Terminus got released 2 days ago, that is now [resolving its dependencies](https://github.com/pantheon-systems/terminus/blob/2.1.0/composer.lock#L2733) to `phpspec/prophecy: 1.8.1` however Terminus Build Tools Plugin project is explicitly depending on `phpspec/prophecy: 1.8.0` (see https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/2.0.0-beta15/composer.json#L21)

As a temporary workaround we downgraded Terminus to version 2.0.1. This way our Gitlab CI works again.

**Comment by greg-1-anderson** [comment] 2019-09-05 14:10
@zserno Are you using the 6.x version of the build-tools-ci docker container? If so, you only need to clear your docker image cache on your CI server, as this bug has been fixed.

**Comment by ataylorme** [comment] 2019-09-05 14:26
If you are installing Terminus and Build Tools yourself they need to be installed with `--no-dev`. Beta 15 of Build Tools added some unit tests, and more dev dependencies, which is why the conflict is surfacing now.

**Comment by ataylorme** [comment] 2019-09-05 14:36
Closing as a duplicate of https://github.com/pantheon-systems/docker-build-tools-ci/issues/36

**Closed by ataylorme** 2019-09-05 14:36 UTC

**Comment by zserno** [comment] 2019-09-05 17:22
Many thanks, @ataylorme! Adding `--no-dev` while installing Terminus Build Tools fixed the problem:

```
$ composer create-project -d ~/.terminus/plugins pantheon-systems/terminus-build-tools-plugin:^2.0.0-beta15 --no-dev
```

**Comment by ataylorme** [comment] 2019-09-05 18:14
@zserno glad to hear it!
