### ISSUE TITLE
`build:env:delete:pr` command uses incorrect GitHub API endpoint

### ISSUE THREAD

**Issue by leehuffman** [pantheon-systems/terminus-build-tools-plugin#143] opened 2018-07-14 01:09 UTC
I'm attempting to use the [one command setup](https://github.com/pantheon-systems/example-wordpress-composer#one-command-setup) from pantheon-systems/example-wordpress-composer. Everything functions correctly until I start in on a branch & pull request.

When operating on a branch & pull request, the `terminus build:env:delete:pr` command that's executed as part of the `deploy-to-pantheon.sh` script appears to use the configured git remote to derive the GitHub API URL. Since CircleCI is using SSH against GitHub, this turns into something like this:

`https://api.github.com/repos/git@github.com:{USER}/{REPOSITORY}.git/pulls?state=closed`

Which returns a 404. Complete output is as follows:
```
 [notice] Call GitHub API: GET repos/git@github.com:{USER}/{REPOSITORY}.git/pulls?state=closed
 [error]  Client error: `GET https://api.github.com/repos/git@github.com:{USER}/{REPOSITORY}.git/pulls?state=closed` resulted in a `404 Not Found` response:
{"message":"Not Found","documentation_url":"https://developer.github.com/v3/pulls/#list-pull-requests"}
```

I believe it should be using `https://api.github.com/repos/{USER}/{REPOSITORY}/pulls?state=closed`.

It looks like the API endpoint is derived from the `url` in `build-metadata.json`.

https://github.com/pantheon-systems/terminus-build-tools-plugin/blob/master/src/Commands/EnvDeleteCommand.php#L150

I wonder if you should be storing `user_org` & `repository` and then using that to produce the Git URL and API URL on the fly? That should map across Git providers as you expand and support additional services.

**Comment by nterbogt** [comment] 2018-09-07 00:39
This is probably the cause of the error I'm seeing.
When I merge a pr-NN branch using circleci 2... my call to `build:env:delete:pr` deletes *all* pr-NN branches... not just the one I merged.

**Comment by omero** [comment] 2018-11-10 04:52
Hey @nterbogt this issue was fixed in issue #128 maybe you need to update your `BUILD_TOOLS_VERSION` environment variable on your circleci config file, at this moment I'm using `^2.0.0-beta1` and works fine

**Comment by greg-1-anderson** [comment] 2019-02-25 17:55
Please try with Build Tools 2.0.0-beta5 (n.b. requires Terminus 2). You can get this in CircleCI by using `- image: quay.io/pantheon-public/build-tools-ci:4.x` in your .circleci/config.yml.

**Comment by ataylorme** [comment] 2019-07-03 16:44
Closing this out due to inactivity. If the issue persists, please re-open or create a new issue

**Closed by ataylorme** 2019-07-03 16:44 UTC

**Comment by ataylorme** [comment] 2019-07-03 16:47
Also note that #171 resolved this but you will need to update your Terminus Build Tools version. You can use `quay.io/pantheon-public/build-tools-ci:6.x`
